# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class BarChart < Data
    attr_reader data: Array[BarChart::BarGroup]
    attr_reader bar_width: Integer
    attr_reader bar_gap: Integer
    attr_reader group_gap: Integer
    attr_reader max: Integer?
    attr_reader style: Style?
    attr_reader block: Block?
    attr_reader direction: :vertical | :horizontal
    attr_reader label_style: Style?
    attr_reader value_style: Style?
    attr_reader bar_set: String?

    def self.new: (
      data: Hash[String | Symbol | _ToS, Numeric] | Array[Array[String | Symbol | _ToS | Numeric]] | Array[BarChart::BarGroup],
      ?bar_width: Numeric,
      ?bar_gap: Numeric,
      ?group_gap: Numeric,
      ?max: Numeric?,
      ?style: Style?,
      ?block: Block?,
      ?direction: :vertical | :horizontal,
      ?label_style: Style?,
      ?value_style: Style?,
      ?bar_set: String?
    ) -> BarChart
  end
end
