# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Block < Data
    attr_reader titles: Array[Hash[Symbol, untyped]]
    def self.new: (?title: String?, ?titles: Array[Hash[Symbol, untyped]], ?title_alignment: Symbol?, ?borders: Array[Symbol], ?border_color: (String | Symbol)?, ?border_type: Symbol?, ?style: (Style | Hash[Symbol, untyped])?, ?padding: (Integer | Array[Integer])) -> Block
  end
end
