# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Block < Data
    attr_reader title: String?
    attr_reader title_alignment: Symbol?
    attr_reader borders: Array[Symbol]
    attr_reader border_color: (String | Symbol)?
    attr_reader border_type: Symbol?
    attr_reader padding: (Integer | Array[Integer])
    def self.new: (?title: String?, ?title_alignment: Symbol?, ?borders: Array[Symbol], ?border_color: (String | Symbol)?, ?border_type: Symbol?, ?padding: (Integer | Array[Integer])) -> Block
  end
end
