# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  module Shape
    class Point < Data
      attr_reader x: Float
      attr_reader y: Float

      def self.new: (x: Numeric, y: Numeric) -> Point
                  | (Numeric, Numeric) -> Point
    end

    class Line < Data
      attr_reader x1: Float
      attr_reader y1: Float
      attr_reader x2: Float
      attr_reader y2: Float
      attr_reader color: String | Symbol

      def self.new: (x1: Numeric, y1: Numeric, x2: Numeric, y2: Numeric, color: String | Symbol) -> Line
                  | (Numeric, Numeric, Numeric, Numeric, String | Symbol) -> Line
    end

    class Rectangle < Data
      attr_reader x: Float
      attr_reader y: Float
      attr_reader width: Float
      attr_reader height: Float
      attr_reader color: String | Symbol

      def self.new: (x: Numeric, y: Numeric, width: Numeric, height: Numeric, color: String | Symbol) -> Rectangle
                  | (Numeric, Numeric, Numeric, Numeric, String | Symbol) -> Rectangle
    end

    class Circle < Data
      attr_reader x: Float
      attr_reader y: Float
      attr_reader radius: Float
      attr_reader color: String | Symbol

      def self.new: (x: Numeric, y: Numeric, radius: Numeric, color: String | Symbol) -> Circle
                  | (Numeric, Numeric, Numeric, String | Symbol) -> Circle
    end

    class Map < Data
      attr_reader color: String | Symbol
      attr_reader resolution: Symbol

      def self.new: (color: String | Symbol, resolution: Symbol) -> Map
                  | (String | Symbol, Symbol) -> Map
    end

    class Label < Data
      attr_reader x: Float
      attr_reader y: Float
      attr_reader text: String | Text::Line
      attr_reader style: Style?

      def self.new: (x: Numeric, y: Numeric, text: String | Text::Line, ?style: Style?) -> Label
    end
  end

  class Canvas < Data
    attr_reader shapes: Array[Shape::Line | Shape::Rectangle | Shape::Circle | Shape::Map | Shape::Label]
    attr_reader x_bounds: Array[Float]
    attr_reader y_bounds: Array[Float]
    attr_reader marker: Symbol
    attr_reader block: Block?

    attr_reader background_color: String | Symbol | nil

    def self.new: (?shapes: Array[Shape::Line | Shape::Rectangle | Shape::Circle | Shape::Map | Shape::Label], ?x_bounds: Array[Numeric], ?y_bounds: Array[Numeric], ?marker: Symbol, ?block: Block?, ?background_color: String | Symbol | nil) -> Canvas
  end
end
