# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Center < Data
    attr_reader child: widget
    attr_reader width_percent: Float
    attr_reader height_percent: Float
    def self.new: (child: widget, ?width_percent: Numeric, ?height_percent: Numeric) -> Center
  end
end
