# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Axis < Data
    attr_reader title: String
    attr_reader bounds: [Float, Float]
    attr_reader labels: Array[String]
    attr_reader style: Style?
    attr_reader labels_alignment: Symbol?
    def self.new: (?title: String, ?bounds: [Numeric, Numeric], ?labels: Array[String], ?style: Style?, ?labels_alignment: Symbol?) -> Axis
  end

  class Dataset < Data
    attr_reader name: String | Symbol
    attr_reader data: Array[[Float, Float]]
    attr_reader style: Style?
    attr_reader marker: Symbol
    attr_reader graph_type: Symbol
    def self.new: (name: String | Symbol, data: Array[[Numeric, Numeric]], ?style: Style?, ?marker: Symbol, ?graph_type: Symbol) -> Dataset
  end

  class Chart < Data
    attr_reader datasets: Array[Dataset]
    attr_reader x_axis: Axis
    attr_reader y_axis: Axis
    attr_reader block: Block?
    attr_reader style: Style?
    attr_reader legend_position: Symbol?
    attr_reader hidden_legend_constraints: Array[Constraint]
    def self.new: (datasets: Array[Dataset], x_axis: Axis, y_axis: Axis, ?block: Block?, ?style: Style?, ?legend_position: Symbol?, ?hidden_legend_constraints: Array[Constraint]) -> Chart
  end

  class LineChart < Data
    attr_reader datasets: Array[Dataset]
    attr_reader x_labels: Array[String]
    attr_reader y_labels: Array[String]
    attr_reader y_bounds: [Float, Float]
    attr_reader block: Block?
    def self.new: (datasets: Array[Dataset], ?x_labels: Array[String], ?y_labels: Array[String], ?y_bounds: [Numeric, Numeric], ?block: Block?) -> LineChart
  end
end
