# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Constraint < Data
    attr_reader type: Symbol
    attr_reader value: (Integer | Array[Integer])
    def self.length: (Integer) -> Constraint
    def self.percentage: (Integer) -> Constraint
    def self.min: (Integer) -> Constraint
    def self.max: (Integer) -> Constraint
    def self.fill: (?Integer) -> Constraint
    def self.ratio: (Integer, Integer) -> Constraint
    def self.new: (type: Symbol, value: (Integer | Array[Integer])) -> Constraint
  end
end
