# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Gauge < Data
    attr_reader ratio: Float
    attr_reader label: String?
    attr_reader style: Style
    attr_reader block: Block?

    def self.new: (?ratio: Float, ?label: String?, ?style: Style, ?block: Block?) -> Gauge
  end
end
