# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Gauge < Data
    attr_reader ratio: Float
    attr_reader label: String?
    attr_reader style: Style?
    attr_reader gauge_style: Style?
    attr_reader block: Block?

    attr_reader use_unicode: bool
    def self.new: (?ratio: Numeric?, ?percent: Numeric?, ?label: String?, ?style: Style?, ?gauge_style: Style?, ?block: Block?, ?use_unicode: bool) -> Gauge
  end
end
