# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  type flex_mode = :legacy | :start | :center | :end | :space_between | :space_around | :space_evenly

  class Layout < Data
    FLEX_MODES: Array[Symbol]

    attr_reader direction: Symbol
    attr_reader constraints: Array[Constraint]
    attr_reader children: Array[widget]
    attr_reader flex: flex_mode
    def self.new: (?direction: Symbol, ?constraints: Array[Constraint], ?children: Array[widget], ?flex: flex_mode) -> Layout
    def self.split: (Rect | Hash[Symbol, Integer] area, ?direction: Symbol, constraints: Array[Constraint], ?flex: flex_mode) -> Array[Rect]

    private

    def self._split: (Rect, Symbol, Array[Constraint], Symbol) -> Array[Hash[Symbol, Integer]]
  end
end
