# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class LineGauge < Data
    attr_reader ratio: Float
    attr_reader label: String?
    attr_reader filled_style: Style?
    attr_reader unfilled_style: Style?
    attr_reader block: Block?
    attr_reader filled_symbol: String
    attr_reader unfilled_symbol: String

    def self.new: (?ratio: Float, ?label: String?, ?filled_style: Style?, ?unfilled_style: Style?, ?block: Block?, ?filled_symbol: String, ?unfilled_symbol: String) -> LineGauge
  end
end
