# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Dataset < Data
    attr_reader name: String | Symbol
    attr_reader data: Array[[Float, Float]]
    attr_reader color: String | Symbol
    def self.new: (name: String | Symbol, data: Array[[Float, Float]], ?color: String | Symbol) -> Dataset
  end

  class LineChart < Data
    attr_reader datasets: Array[Dataset]
    attr_reader x_labels: Array[String]
    attr_reader y_labels: Array[String]
    attr_reader y_bounds: [Float, Float]
    attr_reader block: Block?
    def self.new: (datasets: Array[Dataset], ?x_labels: Array[String], ?y_labels: Array[String], ?y_bounds: [Float, Float], ?block: Block?) -> LineChart
  end
end
