# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class List < Data
    attr_reader items: Array[String]
    attr_reader selected_index: Integer?
    attr_reader style: Style?
    attr_reader highlight_style: Style?
    attr_reader highlight_symbol: String?
    attr_reader repeat_highlight_symbol: bool
    attr_reader highlight_spacing: Symbol
    attr_reader direction: Symbol
    attr_reader scroll_padding: Integer?
    attr_reader block: Block?
    def self.new: (?items: Array[String], ?selected_index: Integer?, ?style: Style?, ?highlight_style: Style?, ?highlight_symbol: String?, ?repeat_highlight_symbol: bool, ?highlight_spacing: Symbol, ?direction: Symbol, ?scroll_padding: Integer?, ?block: Block?) -> List
  end
end
