# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Paragraph < Data
    attr_reader text: String
    attr_reader fg: (String | Symbol)?
    attr_reader bg: (String | Symbol)?
    attr_reader block: Block?
    def self.new: (text: String, ?fg: (String | Symbol)?, ?bg: (String | Symbol)?, ?block: Block?) -> Paragraph
  end
end
