# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Paragraph < Data
    attr_reader text: String
    attr_reader style: Style
    attr_reader block: Block?
    attr_reader wrap: bool
    attr_reader align: Symbol
    attr_reader scroll: [Integer, Integer]
    def self.new: (text: String, ?style: Style?, ?fg: (String | Symbol)?, ?bg: (String | Symbol)?, ?block: Block?, ?wrap: bool, ?align: Symbol, ?scroll: [Numeric, Numeric]) -> Paragraph
  end
end
