# frozen_string_literal: true

# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class RatatuiMascot < Data
    attr_reader block: Block?

    def self.new: (?block: Block?) -> RatatuiMascot
  end
end
