# frozen_string_literal: true

# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Rect < Data
    attr_reader x: Integer
    attr_reader y: Integer
    attr_reader width: Integer
    attr_reader height: Integer
    def self.new: (?x: Numeric, ?y: Numeric, ?width: Numeric, ?height: Numeric) -> instance
    def contains?: (Integer px, Integer py) -> bool
  end
end
