# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Scrollbar < Data
    attr_reader content_length: Integer
    attr_reader position: Integer
    attr_reader orientation: Symbol
    attr_reader thumb_symbol: String
    attr_reader thumb_style: Style?
    attr_reader track_symbol: String?
    attr_reader track_style: Style?
    attr_reader begin_symbol: String?
    attr_reader begin_style: Style?
    attr_reader end_symbol: String?
    attr_reader end_style: Style?
    attr_reader style: Style?
    attr_reader block: Block?

    def self.new: (
      content_length: Numeric,
      position: Numeric,
      ?orientation: Symbol,
      ?thumb_symbol: String,
      ?thumb_style: Style?,
      ?track_symbol: String?,
      ?track_style: Style?,
      ?begin_symbol: String?,
      ?begin_style: Style?,
      ?end_symbol: String?,
      ?end_style: Style?,
      ?style: Style?,
      ?block: Block?
    ) -> Scrollbar
  end
end
