# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Sparkline < Data
    attr_reader data: Array[Integer?]
    attr_reader max: Integer?
    attr_reader style: Style?
    attr_reader block: Block?
    attr_reader direction: (:left_to_right | :right_to_left)?
    attr_reader absent_value_symbol: String?
    attr_reader absent_value_style: Style?
    attr_reader bar_set: Hash[Symbol, String]?
    def self.new: (data: Array[Numeric?], ?max: Numeric?, ?style: Style?, ?block: Block?, ?direction: (:left_to_right | :right_to_left)?, ?absent_value_symbol: String?, ?absent_value_style: Style?, ?bar_set: Hash[Symbol, String]?) -> Sparkline
  end
end
