# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Style < Data
    attr_reader fg: (String | Symbol | Integer)?
    attr_reader bg: (String | Symbol | Integer)?
    attr_reader modifiers: Array[Symbol]

    def self.new: (?fg: (String | Symbol | Integer)?, ?bg: (String | Symbol | Integer)?, ?modifiers: Array[Symbol]) -> Style
    def self.default: () -> Style
  end
end
