# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Table < Data
    attr_reader header: Array[String | Paragraph]?
    attr_reader rows: Array[Array[String | Paragraph | Style | _ToS]]
    attr_reader widths: Array[Constraint]
    attr_reader block: Block?
    attr_reader footer: Array[String | Paragraph]?
    attr_reader flex: Symbol
    attr_reader style: (Style | Hash[Symbol, untyped])?
    attr_reader column_spacing: Integer?
    attr_reader highlight_spacing: Symbol

    def self.new: (?header: Array[String | Paragraph]?, ?rows: Array[Array[String | Paragraph | Style | _ToS]], ?widths: Array[Constraint], ?highlight_style: Style?, ?highlight_symbol: String, ?highlight_spacing: Symbol, ?selected_row: Integer?, ?block: Block?, ?footer: Array[String | Paragraph]?, ?flex: Symbol, ?style: (Style | Hash[Symbol, untyped])?, ?column_spacing: Integer) -> Table
  end
end
