# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Table < Data
    attr_reader header: Array[String]?
    attr_reader rows: Array[Array[String]]
    attr_reader widths: Array[Constraint]
    attr_reader block: Block?

    def self.new: (?header: Array[String]?, ?rows: Array[Array[String]], ?widths: Array[Constraint], ?block: Block?) -> Table
  end
end
