# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  module Text
    class Span < Data
      attr_reader content: String
      attr_reader style: Style?

      def self.new: (content: String, ?style: Style?) -> Span
      def initialize: (content: String, ?style: Style?) -> void
      def self.styled: (String, ?Style?) -> Span
    end

    class Line < Data
      attr_reader spans: Array[Span]
      attr_reader alignment: Symbol?
      attr_reader style: Style?

      def self.new: (?spans: Array[Span], ?alignment: Symbol?, ?style: Style?) -> Line
      def initialize: (?spans: Array[Span], ?alignment: Symbol?, ?style: Style?) -> void
      def self.from_string: (String, ?alignment: Symbol?) -> Line
      def width: () -> Integer
    end

    def self.width: (String) -> Integer
  end
end
