# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  module Text
    class Span < Data
      attr_reader content: String
      attr_reader style: Style | nil

      def initialize: (content: String, style: Style | nil) -> void
      def self.styled: (String, Style | nil) -> Span
    end

    class Line < Data
      attr_reader spans: Array[Span]
      attr_reader alignment: Symbol | nil

      def initialize: (spans: Array[Span], alignment: Symbol | nil) -> void
      def self.from_string: (String, alignment: Symbol | nil) -> Line
      def width: () -> Integer
    end

    def self.width: (String) -> Integer
  end
end
