# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class TUI
    module CanvasFactories
      def shape_map: (?color: (String | Symbol), ?resolution: Symbol) -> Widgets::Shape::Map
      def shape_line: (x1: Numeric, y1: Numeric, x2: Numeric, y2: Numeric, color: (String | Symbol)) -> Widgets::Shape::Line
      def shape_point: (x: Numeric, y: Numeric) -> Widgets::Shape::Point
      def shape_circle: (x: Numeric, y: Numeric, radius: Numeric, color: (String | Symbol)) -> Widgets::Shape::Circle
      def shape_rectangle: (x: Numeric, y: Numeric, width: Numeric, height: Numeric, color: (String | Symbol)) -> Widgets::Shape::Rectangle
    end
  end
end
