# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

image: archlinux
packages:
  - ruby
  - rust
  - cargo
  - make
  - gcc
  - clang
sources:
  - https://git.sr.ht/~kerrick/ratatui_ruby
tasks:
  - setup: |
      cd ratatui_ruby
      export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
      gem install --user-install bundler -v 2.6.9
      bundle config set --local path 'vendor/bundle'
      bundle install
  - test: |
      cd ratatui_ruby
      export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
      bundle config set --local path 'vendor/bundle'
      # Compile the extension before running tests
      bundle exec rake compile
      # Run the test suite (Headless)
      bundle exec rake test
  - package: |
      cd ratatui_ruby
      export PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
      bundle config set --local path 'vendor/bundle'
      # Verify packaging works
      gem build ratatui_ruby.gemspec
