# frozen_string_literal: true

# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

# !!! DO NOT EDIT THIS FILE BY HAND !!!
# This file is automatically generated by `rake autodoc:rdoc:session`.
# Any changes will be overwritten.

module RatatuiRuby
  class Session
    # == RatatuiRuby Delegates
    #
    # :method: _paragraph_line_count
    # :call-seq: _paragraph_line_count(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby._paragraph_line_count.
    #
    # :method: _paragraph_line_width
    # :call-seq: _paragraph_line_width(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby._paragraph_line_width.
    #
    # :method: _tabs_width
    # :call-seq: _tabs_width(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby._tabs_width.
    #
    # :method: _text_width
    # :call-seq: _text_width(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby._text_width.
    #
    # :method: clear_events
    # :call-seq: clear_events(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.clear_events.
    #
    # :method: draw
    # :call-seq: draw(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.draw.
    #
    # :method: experimental_warnings
    # :call-seq: experimental_warnings(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.experimental_warnings.
    #
    # :method: experimental_warnings=
    # :call-seq: experimental_warnings=(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.experimental_warnings=.
    #
    # :method: get_buffer_content
    # :call-seq: get_buffer_content(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.get_buffer_content.
    #
    # :method: get_cell_at
    # :call-seq: get_cell_at(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.get_cell_at.
    #
    # :method: get_cursor_position
    # :call-seq: get_cursor_position(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.get_cursor_position.
    #
    # :method: init_terminal
    # :call-seq: init_terminal(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.init_terminal.
    #
    # :method: init_test_terminal
    # :call-seq: init_test_terminal(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.init_test_terminal.
    #
    # :method: inject_test_event
    # :call-seq: inject_test_event(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.inject_test_event.
    #
    # :method: poll_event
    # :call-seq: poll_event(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.poll_event.
    #
    # :method: resize_terminal
    # :call-seq: resize_terminal(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.resize_terminal.
    #
    # :method: restore_terminal
    # :call-seq: restore_terminal(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.restore_terminal.
    #
    # :method: run
    # :call-seq: run(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.run.
    #
    # :method: warn_experimental_feature
    # :call-seq: warn_experimental_feature(*args, **kwargs, &block)
    #
    # Delegates to RatatuiRuby.warn_experimental_feature.
    #
    # == Widget Factories
    #
    # :method: draw_cell
    # :call-seq: draw_cell(*args, **kwargs, &block)
    #
    # Helper for RatatuiRuby::Draw.cell.
    #
    # :method: draw_string
    # :call-seq: draw_string(*args, **kwargs, &block)
    #
    # Helper for RatatuiRuby::Draw.string.
    #
    # :method: draw_cell_cmd
    # :call-seq: draw_cell_cmd(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Draw::CellCmd.new.
    #
    # :method: draw_string_cmd
    # :call-seq: draw_string_cmd(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Draw::StringCmd.new.
    #
    # :method: error
    # :call-seq: error(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Error.new.
    #
    # :method: error_safety
    # :call-seq: error_safety(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Error::Safety.new.
    #
    # :method: error_terminal
    # :call-seq: error_terminal(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Error::Terminal.new.
    #
    # :method: event
    # :call-seq: event(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Event.new.
    #
    # :method: event_focus_gained
    # :call-seq: event_focus_gained(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Event::FocusGained.new.
    #
    # :method: event_focus_lost
    # :call-seq: event_focus_lost(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Event::FocusLost.new.
    #
    # :method: event_key
    # :call-seq: event_key(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Event::Key.new.
    #
    # :method: event_mouse
    # :call-seq: event_mouse(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Event::Mouse.new.
    #
    # :method: event_none
    # :call-seq: event_none(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Event::None.new.
    #
    # :method: event_paste
    # :call-seq: event_paste(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Event::Paste.new.
    #
    # :method: event_resize
    # :call-seq: event_resize(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Event::Resize.new.
    #
    # :method: frame
    # :call-seq: frame(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Frame.new.
    #
    # :method: layout_constraint
    # :call-seq: layout_constraint(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Layout::Constraint.new.
    #
    # :method: layout_layout
    # :call-seq: layout_layout(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Layout::Layout.new.
    #
    # :method: layout_rect
    # :call-seq: layout_rect(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Layout::Rect.new.
    #
    # :method: list_state
    # :call-seq: list_state(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::ListState.new.
    #
    # :method: list_state_new
    # :call-seq: list_state_new(*args, **kwargs, &block)
    #
    # Helper for RatatuiRuby::ListState.new.
    #
    # :method: scrollbar_state
    # :call-seq: scrollbar_state(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::ScrollbarState.new.
    #
    # :method: scrollbar_state_new
    # :call-seq: scrollbar_state_new(*args, **kwargs, &block)
    #
    # Helper for RatatuiRuby::ScrollbarState.new.
    #
    # :method: style_style
    # :call-seq: style_style(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Style::Style.new.
    #
    # :method: table_state
    # :call-seq: table_state(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::TableState.new.
    #
    # :method: table_state_new
    # :call-seq: table_state_new(*args, **kwargs, &block)
    #
    # Helper for RatatuiRuby::TableState.new.
    #
    # :method: text_width
    # :call-seq: text_width(*args, **kwargs, &block)
    #
    # Helper for RatatuiRuby::Text.width.
    #
    # :method: text_line
    # :call-seq: text_line(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Text::Line.new.
    #
    # :method: text_span
    # :call-seq: text_span(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Text::Span.new.
    #
    # :method: widgets_axis
    # :call-seq: widgets_axis(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Axis.new.
    #
    # :method: widgets_bar_chart
    # :call-seq: widgets_bar_chart(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::BarChart.new.
    #
    # :method: widgets_block
    # :call-seq: widgets_block(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Block.new.
    #
    # :method: widgets_calendar
    # :call-seq: widgets_calendar(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Calendar.new.
    #
    # :method: widgets_canvas
    # :call-seq: widgets_canvas(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Canvas.new.
    #
    # :method: widgets_cell
    # :call-seq: widgets_cell(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Cell.new.
    #
    # :method: widgets_center
    # :call-seq: widgets_center(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Center.new.
    #
    # :method: widgets_chart
    # :call-seq: widgets_chart(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Chart.new.
    #
    # :method: widgets_clear
    # :call-seq: widgets_clear(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Clear.new.
    #
    # :method: widgets_cursor
    # :call-seq: widgets_cursor(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Cursor.new.
    #
    # :method: widgets_dataset
    # :call-seq: widgets_dataset(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Dataset.new.
    #
    # :method: widgets_gauge
    # :call-seq: widgets_gauge(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Gauge.new.
    #
    # :method: widgets_line_chart
    # :call-seq: widgets_line_chart(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::LineChart.new.
    #
    # :method: widgets_line_gauge
    # :call-seq: widgets_line_gauge(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::LineGauge.new.
    #
    # :method: widgets_list
    # :call-seq: widgets_list(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::List.new.
    #
    # :method: widgets_list_item
    # :call-seq: widgets_list_item(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::ListItem.new.
    #
    # :method: widgets_overlay
    # :call-seq: widgets_overlay(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Overlay.new.
    #
    # :method: widgets_paragraph
    # :call-seq: widgets_paragraph(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Paragraph.new.
    #
    # :method: widgets_ratatui_logo
    # :call-seq: widgets_ratatui_logo(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::RatatuiLogo.new.
    #
    # :method: widgets_ratatui_mascot
    # :call-seq: widgets_ratatui_mascot(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::RatatuiMascot.new.
    #
    # :method: widgets_row
    # :call-seq: widgets_row(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Row.new.
    #
    # :method: widgets_scrollbar
    # :call-seq: widgets_scrollbar(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Scrollbar.new.
    #
    # :method: widgets_sparkline
    # :call-seq: widgets_sparkline(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Sparkline.new.
    #
    # :method: widgets_table
    # :call-seq: widgets_table(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Table.new.
    #
    # :method: widgets_tabs
    # :call-seq: widgets_tabs(*args, **kwargs, &block)
    #
    # Factory for RatatuiRuby::Widgets::Tabs.new.
    #
  end
end
