# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class BlockTitlesApp
  # @public
  def self.new: () -> BlockTitlesApp

  # @public
  def run: () -> void
end
