# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
#++

require "fileutils"

# The generated Minitest file for Event::Key predicates.
# The tests know how to persist themselves to disk.
class PredicateTests < Data.define(:catalog, :output_path)
  DEFAULT_OUTPUT = File.expand_path("../../test/generated/event_key_predicates_test.rb", __dir__)

  def initialize(catalog:, output_path: DEFAULT_OUTPUT)
    super
  end

  def persist!
    FileUtils.mkdir_p(File.dirname(output_path))
    File.write(output_path, to_ruby)
    puts "Generated #{test_methods.size} tests to #{output_path}"
  end

  def to_ruby
    <<~RUBY
      # frozen_string_literal: true
      
      #--
      # SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
      # SPDX-License-Identifier: AGPL-3.0-or-later
      #++
      
      # \u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557
      # \u2551                     \u26a0\ufe0f  DO NOT EDIT THIS FILE  \u26a0\ufe0f                  \u2551
      # \u2551                                                                   \u2551
      # \u2551  This file is auto-generated by: rake rbs:tests                   \u2551
      # \u2551  Any manual changes will be overwritten on next generation.       \u2551
      # \u2551                                                                   \u2551
      # \u2551  To modify tests, edit: tasks/rbs_predicates/predicate_tests.rb   \u2551
      # \u255a\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255d
      
      require "test_helper"
      
      class GeneratedEventKeyPredicatesTest < Minitest::Test
        include RatatuiRuby::TestHelper
      
      #{test_methods.map { |t| t.to_s.gsub(/^/, '  ') }.join("\n\n")}
      end
    RUBY
  end

  private def test_methods
    simple_tests + combo_tests
  end

  private def simple_tests
    catalog.all_base_codes.map { |code| SimplePredicateTest.new(code) }
  end

  private def combo_tests
    sampled_combos.map { |combo| ModifierComboTest.new(combo) }
  end

  private def sampled_combos
    sample_keys = %w[a enter up f1]
    catalog.modifier_combinations.product(sample_keys).map { |mods, key| mods + [key] }
  end

  # A single predicate test that knows how to render itself.
  class SimplePredicateTest < Data.define(:code)
    VALID_IDENTIFIER = /\A[a-z_][a-z0-9_]*\?\z/i

    def to_s
      <<~RUBY.chomp
        def test_#{method_name}_predicate
          RatatuiRuby.inject_test_event("key", { code: #{code.inspect} })
          event = RatatuiRuby.poll_event
          #{assertion}
        end
      RUBY
    end

    private def predicate = "#{code}?"
    private def method_name = code.gsub(/[^a-z0-9_]/i) { |c| "_#{c.ord}_" }

    private def assertion
      if predicate.match?(VALID_IDENTIFIER)
        "assert event.#{predicate}"
      else
        "assert event.public_send(#{predicate.inspect})"
      end
    end
  end

  # A modifier + key combo test that knows how to render itself.
  class ModifierComboTest < Data.define(:combo)
    VALID_IDENTIFIER = /\A[a-z_][a-z0-9_]*\?\z/i

    def to_s
      <<~RUBY.chomp
        def test_#{method_name}_predicate
          RatatuiRuby.inject_test_event("key", { code: #{key.inspect}, modifiers: [#{mods_array}] })
          event = RatatuiRuby.poll_event
          #{assertion}
        end
      RUBY
    end

    private def key = combo.last
    private def mods = combo[0...-1]
    private def mods_array = mods.map(&:inspect).join(", ")
    private def predicate = "#{combo.join('_')}?"
    private def method_name = combo.join("_").gsub(/[^a-z0-9_]/i) { |c| "_#{c.ord}_" }

    private def assertion
      if predicate.match?(VALID_IDENTIFIER)
        "assert event.#{predicate}"
      else
        "assert event.public_send(#{predicate.inspect})"
      end
    end
  end
end
