# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
#++

# RBS signature file for Event::Key predicates.
class RbsSignature < Data.define(:catalog, :output_path)
  DEFAULT_OUTPUT = File.expand_path("../../sig/generated/event_key_predicates.rbs", __dir__)

  def initialize(catalog:, output_path: DEFAULT_OUTPUT)
    super
  end

  def write
    FileUtils.mkdir_p(File.dirname(output_path))
    File.write(output_path, content)
    puts "Generated #{catalog.all_predicates.size} predicates to #{output_path}"
  end

  def content
    <<~RBS
      # SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
      # SPDX-License-Identifier: LGPL-3.0-or-later
      #
      # ╔═══════════════════════════════════════════════════════════════════╗
      # ║                     ⚠️  DO NOT EDIT THIS FILE  ⚠️                 ║
      # ║                                                                   ║
      # ║  This file is auto-generated by: rake rbs:predicates              ║
      # ║  Any manual changes will be overwritten on next generation.       ║
      # ║                                                                   ║
      # ║  To modify predicates, edit the source in:                        ║
      # ║    - ext/ratatui_ruby/src/events.rs (key mappings)                ║
      # ║    - tasks/rbs_predicates/predicate_catalog.rb                    ║
      # ╚═══════════════════════════════════════════════════════════════════╝

      module RatatuiRuby
        class Event
          class Key < Event
      #{predicate_declarations.map { |d| "      #{d}" }.join("\n")}
          end
        end
      end
    RBS
  end

  private def predicate_declarations
    catalog.all_predicates.map { |name| rbs_method_def(name) }
  end

  # Valid Ruby method identifier: starts with letter/underscore, followed by word chars, optional ?
  VALID_PREDICATE_PATTERN = /\A[a-z_][a-z0-9_]*\?\z/i

  def rbs_method_def(name)
    method_name = "#{name}?"
    if method_name.match?(VALID_PREDICATE_PATTERN)
      "def #{method_name}: () -> bool"
    else
      "def `#{method_name}`: () -> bool"
    end
  end
end
