# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

class WidgetRect
  MENU_ITEMS: Array[String]

  # @public
  def self.new: () -> WidgetRect

  # @public
  def run: () -> void
end
