# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: MIT-0
#++

#
# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

class WidgetBlockDemo
  @tui: RatatuiRuby::TUI
  @hotkey_style: RatatuiRuby::Style
  @title_configs: Array[{name: String, title: String?}]
  @title_index: Integer
  @titles_configs: Array[{name: String, titles: Array[untyped]}]
  @titles_index: Integer
  @alignment_configs: Array[{name: String, alignment: Symbol}]
  @alignment_index: Integer
  @title_styles: Array[{name: String, style: RatatuiRuby::Style?}]
  @title_style_index: Integer
  @border_configs: Array[{name: String, borders: Array[Symbol]}]
  @border_index: Integer
  @border_type_configs: Array[{name: String, type: Symbol?, set: Hash[Symbol, String]?}]
  @border_type_index: Integer
  @border_styles: Array[{name: String, style: RatatuiRuby::Style?}]
  @border_style_index: Integer
  @base_styles: Array[{name: String, style: RatatuiRuby::Style?}]
  @base_style_index: Integer
  @padding_configs: Array[{name: String, padding: (Integer | Array[Integer])}]
  @padding_index: Integer

  def self.new: () -> WidgetBlockDemo
  def run: () -> void
  private def render: () -> void
  private def handle_input: () -> (:quit)?
end
