# frozen_string_literal: true

# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module Autodoc
  class Notice < Data.define(:task_name)
    def rbs
      [
        "# !!! DO NOT EDIT THIS FILE BY HAND !!!",
        "# This file is automatically generated by `rake #{task_name}`.",
        "# Any changes will be overwritten.",
        "",
      ]
    end

    def rdoc
      [
        "# !!! DO NOT EDIT THIS FILE BY HAND !!!",
        "# This file is automatically generated by `rake #{task_name}`.",
        "# Any changes will be overwritten.",
        "",
      ]
    end
  end
end
