# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class MouseEventsApp
  # @public
  def self.new: () -> MouseEventsApp

  # @public
  def run: () -> void
end
