# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class LoginFormApp
  # @public
  def self.new: () -> LoginFormApp

  # @public
  def run: () -> void
end
