# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

class SparklineDemoApp
  # @public
  def self.new: () -> SparklineDemoApp

  # @public
  def run: () -> void
end
