# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  module Widgets
    class Gauge < Data
      attr_reader ratio: Float
      attr_reader label: (String | Text::Span)?
      attr_reader style: Style?
      attr_reader gauge_style: Style?
      attr_reader block: Block?
      attr_reader use_unicode: bool

      def self.new: (?ratio: Numeric?, ?percent: Numeric?, ?label: String | Text::Span | nil, ?style: Style?, ?gauge_style: Style?, ?block: Block?, ?use_unicode: bool) -> Gauge
      def initialize: (?ratio: Numeric?, ?percent: Numeric?, ?label: String | Text::Span | nil, ?style: Style?, ?gauge_style: Style?, ?block: Block?, ?use_unicode: bool) -> void

      def filled?: () -> bool
      def complete?: () -> bool
    end
  end
end
