# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  module Widgets
    # Options hash type for Tabs constructor arguments.
    type tabs_options = {
      ?titles: Array[String | _ToS],
      ?selected_index: _ToI,
      ?block: Widgets::Block?,
      ?divider: String?,
      ?highlight_style: Style::Style?,
      ?style: Style::Style?,
      ?padding_left: (String | Text::Line | _ToI),
      ?padding_right: (String | Text::Line | _ToI)
    }

    class Tabs < Data
      attr_reader titles: Array[String | _ToS]
      attr_reader selected_index: Integer
      attr_reader block: Widgets::Block?
      attr_reader divider: String?
      attr_reader highlight_style: Style::Style?
      attr_reader style: Style::Style?
      attr_reader padding_left: Integer
      attr_reader padding_right: Integer

      include CoerceableWidget

      def self.coerce_args: (tabs_options first, ?tabs_options kwargs) -> Tabs
                          | (nil first, tabs_options kwargs) -> Tabs

      def self.new: (?titles: Array[String | _ToS], ?selected_index: _ToI, ?block: Widgets::Block?, ?divider: String?, ?highlight_style: Style::Style?, ?style: Style::Style?, ?padding_left: (String | Text::Line | _ToI), ?padding_right: (String | Text::Line | _ToI)) -> Tabs
      def initialize: (?titles: Array[String | _ToS], ?selected_index: _ToI, ?block: Widgets::Block?, ?divider: String?, ?highlight_style: Style::Style?, ?style: Style::Style?, ?padding_left: (String | Text::Line | _ToI), ?padding_right: (String | Text::Line | _ToI)) -> void
      def width: () -> Integer
    end
  end
end
