# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  # Style module at RatatuiRuby::Style
  module Style
    # Style class for RatatuiRuby::Style::Style
    class Style < Data
      type color = String | Symbol | Integer

      attr_reader fg: color?
      attr_reader bg: color?
      attr_reader underline_color: color?
      attr_reader modifiers: Array[Symbol]
      attr_reader remove_modifiers: Array[Symbol]

      def self.new: (?fg: color?, ?bg: color?, ?underline_color: color?, ?modifiers: Array[Symbol], ?remove_modifiers: Array[Symbol]) -> Style
      def initialize: (?fg: color?, ?bg: color?, ?underline_color: color?, ?modifiers: Array[Symbol], ?remove_modifiers: Array[Symbol]) -> void
      def self.default: () -> Style
      def self.with: (?fg: color?, ?bg: color?, ?underline_color: color?, ?modifiers: Array[Symbol], ?remove_modifiers: Array[Symbol]) -> Style
    end
  end
end
