# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  module Widgets
    module Shape
      # Options hash type for Shape::Label constructor arguments.
      type label_options = {
        ?x: _ToF,
        ?y: _ToF,
        ?text: String | Text::Line,
        ?style: Style::Style?
      }

      class Label < Data
        attr_reader x: Float
        attr_reader y: Float
        attr_reader text: String | Text::Line
        attr_reader style: Style::Style?

        include CoerceableWidget

        def self.coerce_args: (label_options first, ?label_options kwargs) -> Label
                            | (nil first, label_options kwargs) -> Label

        def self.new: (x: _ToF, y: _ToF, text: String | Text::Line, ?style: Style::Style?) -> Label
        def initialize: (x: _ToF, y: _ToF, text: String | Text::Line, ?style: Style::Style?) -> void
      end
    end
  end
end
