# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class AppAnalytics
  # @public
  def self.new: () -> AppAnalytics

  # @public
  def run: () -> void
end
