# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class BarChart
    class Bar < Data
      attr_reader value: Integer
      attr_reader label: (String | Text::Span | Text::Line)?
      attr_reader style: Style?
      attr_reader value_style: Style?
      attr_reader text_value: (String | Text::Span | Text::Line)?

      def self.new: (value: Numeric, ?label: String | Text::Span | Text::Line | nil, ?style: Style?, ?value_style: Style?, ?text_value: String | Text::Span | Text::Line | nil) -> Bar
      def initialize: (value: Numeric, ?label: String | Text::Span | Text::Line | nil, ?style: Style?, ?value_style: Style?, ?text_value: String | Text::Span | Text::Line | nil) -> void
    end
  end
end
