# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class BarChart
    class Bar < Data
      attr_reader value: Integer
      attr_reader label: String?
      attr_reader style: Style?
      attr_reader value_style: Style?
      attr_reader text_value: String?

      def self.new: (value: Numeric, ?label: String?, ?style: Style?, ?value_style: Style?, ?text_value: String?) -> Bar
    end
  end
end
