# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

class ViewState < Data
  attr_reader events: Events
  attr_reader focused: bool
  attr_reader hotkey_style: RatatuiRuby::Style
  attr_reader dimmed_style: RatatuiRuby::Style
  attr_reader lit_style: RatatuiRuby::Style
  attr_reader border_color: Symbol
  attr_reader area: RatatuiRuby::Rect?

  def self.build(events: Events, focused: bool, tui: RatatuiRuby::Session, _resize_sub_counter: untyped) -> instance
  def self.new: (?events: Events, ?focused: bool, ?hotkey_style: RatatuiRuby::Style, ?dimmed_style: RatatuiRuby::Style, ?lit_style: RatatuiRuby::Style, ?border_color: Symbol, ?area: RatatuiRuby::Rect | nil) -> instance
end
