# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  # Schema Constraint - defined directly under RatatuiRuby namespace.
  class Constraint < Data
    attr_reader type: Symbol
    attr_reader value: (Integer | Array[Integer])

    def self.new: (type: Symbol, value: (Integer | Array[Integer])) -> Constraint
    def initialize: (type: Symbol, value: (Integer | Array[Integer])) -> void

    def self.length: (_ToI) -> Constraint
    def self.percentage: (_ToI) -> Constraint
    def self.min: (_ToI) -> Constraint
    def self.max: (_ToI) -> Constraint
    def self.fill: (?_ToI) -> Constraint
    def self.ratio: (_ToI, _ToI) -> Constraint
  end
end
