# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

module RatatuiRuby
  module Draw
    class StringCmd < Data
      attr_reader x: Integer
      attr_reader y: Integer
      attr_reader string: String
      attr_reader style: style_input

      def self.new: (x: Integer, y: Integer, string: String, style: style_input) -> StringCmd
    end

    class CellCmd < Data
      attr_reader x: Integer
      attr_reader y: Integer
      attr_reader cell: Buffer::Cell

      def self.new: (x: Integer, y: Integer, cell: Buffer::Cell) -> CellCmd
    end

    def self.string: (_ToI x, _ToI y, String string, ?style_input style) -> StringCmd
    def self.cell: (_ToI x, _ToI y, Buffer::Cell cell) -> CellCmd
  end
end
