# SPDX-FileCopyrightText: 2025 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

module RatatuiRuby
  class Frame
    def area: () -> Rect
    def render_widget: (widget widget, Rect area) -> nil
  end
end
