# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

# Type alias for any Event subtype.
type event_type = RatatuiRuby::Event::Key
               | RatatuiRuby::Event::Mouse
               | RatatuiRuby::Event::Resize
               | RatatuiRuby::Event::Paste
               | RatatuiRuby::Event::FocusGained
               | RatatuiRuby::Event::FocusLost
               | RatatuiRuby::Event::None

class EventEntry < Data
  attr_reader event: event_type
  attr_reader color: Symbol
  attr_reader timestamp: Timestamp

  def self.create: (event_type event, Symbol color, Timestamp timestamp) -> instance
  def type: () -> Symbol
  def description: () -> String
  def matches_type?: (Symbol check_type) -> bool
  def live_type: () -> Symbol
end
